### ISSUE TITLE
Parser fails with "A block may only be used inside an HTML element or another block."

### ISSUE THREAD

**Issue by cangoektas** [glimmerjs/glimmer-vm#1233] opened 2020-12-11 14:07 UTC
Hey! I came across this project and although I realize it's still under development, I wanted to raise an issue that I came across just to understand what's causing it and see if there's a way we could fix it.

---

## Description

Parsing the following text fails:

```
<div class="foo{{#if someCondition}} bar{{/if}}"</div>
```

The error that is thrown says:

> A block may only be used inside an HTML element or another block.

We use Handlebars to compile our templates, and we also use this syntax heavily. I was surprised to see that parsing this is not possible since compiling it with Handlebars and calling the template function does work:

```js
const template = Handlebars.compile(`<div class="foo{{#if someCondition}} bar{{/if}}"</div>`);

console.log(template({ someCondition: true }));
// <div class="foo bar"></div>
```

## Minimal, reproducible example

You can paste the snippet from above into [AST explorer](https://astexplorer.net/) and compare the output between `handlebars` and `glimmer`. `handlebars` is able to parse the code whereas `glimmer` returns an error.

---

Could anybody shed some like into this issue? Is this project planning on being compatible with the Handlebars parser or is this a known issue and the expected behavior?

**Comment by lifeart** [comment] 2020-12-11 14:22
@cangoektas your case should be 

<div class="foo{{if someCondition “ bar”}}"</div>

**Comment by cangoektas** [comment] 2020-12-14 11:00
Thanks @lifeart! That's already really helpful. That seems like an easy and straight forward work-around. Maybe before I close this issue, do you know of any other prohibited Handlebars expressions in glimmer/ember? I was under the impression that valid Handlebars template = valid glimmer/ember templates but this doesn't seem to be the case.

**Comment by lifeart** [comment] 2020-12-14 11:26
@cangoektas some points could be found https://guides.emberjs.com/release/upgrading/current-edition/templates/
Main difference - is blocks is not allowed inside elements.

**Comment by locks** [comment] 2020-12-14 15:22
Closing as this is by design. Thanks for reaching out and thanks for helping OP out!

**Closed by locks** 2020-12-14 15:22 UTC
